### ISSUE TITLE
MIDI file playlist?

### ISSUE THREAD

**Issue by mxmilkiib** [brummer10/Mamba#23]
Being able to just load a directory of MIDI files so as to loop though them sequentially and back again to the start after (or randomly, etc.) for a bit of variety (beyond just one file) whilst testing.

**Comment by brummer10** [comment]
Seems a bit out of scope for Mamba, but a interesting challenge to implement that.

**Comment by brummer10** [comment]
As a first step I've implemented drag'n drop, so you could drop a MIDI file from your File-manager to the keyboard in order to load it. (You don't need to stop playing in order to load a new file). 
Maybe I'll implement a list so that the new file will loaded after the current one is finished, let's see.
The very same work for SoundFonts now, just drop them on the Keyboard to switch the SoundFont in use.
True, when you switch the SoundFont, Mamba roll back the loaded MIDI file to start position in order to reload it's Channel/Instrument settings 
But I guess that will nevertheless allow quickly testing stuff out.

**Comment by brummer10** [comment]
So, not a play list, but now you could add MIDI files to the running loop.

**Comment by brummer10** [comment]
. . . and now, there is a option to remove the last loaded MIDI file.

**Comment by brummer10** [comment]
so now there is a dynamic file remove menu, allow to remove a selected file, not only the last one, from the loop.

**Comment by brummer10** [comment]
will close this issue now, as it is basically solved in the mean of this project.
